name: .NET 10 Azure Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: dotnet publish
      # BasicWeb10 klasöründeki projeyi derleyip içine .NET 10'u paketler
      run: dotnet publish BasicWeb10/BasicWeb10.csproj -c Release -r linux-x64 --self-contained true -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'BasicWeb' # Burası Azure'daki App Service adınla (BasicWeb) aynı olmalı
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish